production:
  mysql41: 9307
  morphology: stem_ru
  charset_type: utf-8
  html_strip: 1
  bin_path: "/usr/bin/X11/"
  host: 127.0.0.1
development:
  mysql41: 9306
  morphology: stem_ru
  charset_type: utf-8
  html_strip: 1
  bin_path: "/usr/bin/X11/"
  host: 127.0.0.1